# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_root = File.basename(File.dirname(__FILE__))

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = true
  config.vm.hostname = vagrant_root
  config.vm.define vagrant_root do |foo|
  end

  # Specify VirtualBox parameters
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = config.vm.hostname
  end

  # Update and install core necessities
  config.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
      apt-get -y upgrade
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
      apt-get -y install make pkg-config bridge-utils socat bindfs
  SHELL

  # Install golang
  config.vm.provision "shell", inline: <<-SHELL
      wget https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz -O go.tar.gz -q
      tar -C /usr/local -xzf go.tar.gz
      rm go.tar.gz
  SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
      echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
  SHELL

  # Install runc
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
      PATH=$PATH:/usr/local/go/bin go get github.com/opencontainers/runc
      cd ~/go/src/github.com/opencontainers/runc
      git checkout v1.0.0-rc7
      PATH=$PATH:/usr/local/go/bin/ make BUILDTAGS=""
      sudo make install
  SHELL
end
